name: Coveralls
on:
  workflow_run:
#    workflows: ["Ruby"]
    types: [completed]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls
      uses: coverallsapp/github-action@v2
